/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginCredentials,
  Meal,
  TopUpRequest,
  User
} from '.././models';




  /**
 * Adds funds to the user's account balance.
 * @summary Top up user balance
 */
export const topUp = <TData = AxiosResponse<number>>(
    topUpRequest: TopUpRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/users/topup`,
      topUpRequest,options
    );
  }
/**
 * Authenticates a user with username and password.
 * @summary User login
 */
export const login = <TData = AxiosResponse<User>>(
    loginCredentials: LoginCredentials, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/users/login`,
      loginCredentials,options
    );
  }
/**
 * Retrieves a list of all users.
 * @summary Get all users
 */
export const getAllUsers = <TData = AxiosResponse<User[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users`,options
    );
  }
/**
 * Retrieves detailed information about a specific user by their ID.
 * @summary Get user by ID
 */
export const getUserById = <TData = AxiosResponse<User>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users/${id}`,options
    );
  }
/**
 * Retrieves a list of meals ordered by the user.
 * @summary Get user meal history
 */
export const getUserHistory = <TData = AxiosResponse<Meal[]>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users/${id}/history`,options
    );
  }
/**
 * Retrieves the current balance of a user by their ID.
 * @summary Get user balance
 */
export const getUserBalance = <TData = AxiosResponse<number>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users/${id}/balance`,options
    );
  }
export type TopUpResult = AxiosResponse<number>
export type LoginResult = AxiosResponse<User>
export type GetAllUsersResult = AxiosResponse<User[]>
export type GetUserByIdResult = AxiosResponse<User>
export type GetUserHistoryResult = AxiosResponse<Meal[]>
export type GetUserBalanceResult = AxiosResponse<number>
