/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  Meal,
  TopUpRequest,
  User
} from '.././models';

import { api } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUsers = () => {
/**
 * Adds funds to the user's account balance.
 * @summary Top up user balance
 */
const topUp = (
    topUpRequest: TopUpRequest,
 options?: SecondParameter<typeof api<number>>,) => {
      return api<number>(
      {url: `/users/topup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: topUpRequest
    },
      options);
    }
  /**
 * Retrieves a list of all users.
 * @summary Get all users
 */
const getAllUsers = (
    
 options?: SecondParameter<typeof api<User[]>>,) => {
      return api<User[]>(
      {url: `/users`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves detailed information about a specific user by their ID.
 * @summary Get user by ID
 */
const getUserById = (
    id: number,
 options?: SecondParameter<typeof api<User>>,) => {
      return api<User>(
      {url: `/users/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves a list of meals ordered by the user.
 * @summary Get user meal history
 */
const getUserHistory = (
    id: number,
 options?: SecondParameter<typeof api<Meal[]>>,) => {
      return api<Meal[]>(
      {url: `/users/${id}/history`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves the current balance of a user by their ID.
 * @summary Get user balance
 */
const getUserBalance = (
    id: number,
 options?: SecondParameter<typeof api<number>>,) => {
      return api<number>(
      {url: `/users/${id}/balance`, method: 'GET'
    },
      options);
    }
  return {topUp,getAllUsers,getUserById,getUserHistory,getUserBalance}};
export type TopUpResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['topUp']>>>
export type GetAllUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getAllUsers']>>>
export type GetUserByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getUserById']>>>
export type GetUserHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getUserHistory']>>>
export type GetUserBalanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getUserBalance']>>>
