/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  LoginCredentials,
  Meal,
  TopUpRequest,
  User
} from '.././models';

import { api } from '.././axios';



  export const getUsers = () => {
/**
 * Adds funds to the user's account balance.
 * @summary Top up user balance
 */
const topUp = (
    topUpRequest: TopUpRequest,
 ) => {
      return api<number>(
      {url: `/users/topup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: topUpRequest
    },
      );
    }
  /**
 * Authenticates a user with username and password.
 * @summary User login
 */
const login = (
    loginCredentials: LoginCredentials,
 ) => {
      return api<User>(
      {url: `/users/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginCredentials
    },
      );
    }
  /**
 * Retrieves a list of all users.
 * @summary Get all users
 */
const getAllUsers = (
    
 ) => {
      return api<User[]>(
      {url: `/users`, method: 'GET'
    },
      );
    }
  /**
 * Retrieves detailed information about a specific user by their ID.
 * @summary Get user by ID
 */
const getUserById = (
    id: number,
 ) => {
      return api<User>(
      {url: `/users/${id}`, method: 'GET'
    },
      );
    }
  /**
 * Retrieves a list of meals ordered by the user.
 * @summary Get user meal history
 */
const getUserHistory = (
    id: number,
 ) => {
      return api<Meal[]>(
      {url: `/users/${id}/history`, method: 'GET'
    },
      );
    }
  /**
 * Retrieves the current balance of a user by their ID.
 * @summary Get user balance
 */
const getUserBalance = (
    id: number,
 ) => {
      return api<number>(
      {url: `/users/${id}/balance`, method: 'GET'
    },
      );
    }
  return {topUp,login,getAllUsers,getUserById,getUserHistory,getUserBalance}};
export type TopUpResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['topUp']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['login']>>>
export type GetAllUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getAllUsers']>>>
export type GetUserByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getUserById']>>>
export type GetUserHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getUserHistory']>>>
export type GetUserBalanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['getUserBalance']>>>
