/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Standard API error response
 */
export interface ApiErrorResponse {
  /** Timestamp of the error */
  timestamp?: string;
  /** HTTP status code */
  status?: number;
  /** HTTP error reason */
  error?: string;
  /** Detailed error message */
  message?: string;
}
