/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BuffetItem } from './buffetItem';

export interface BuffetMenu {
  snacks?: BuffetItem[];
  drinks?: BuffetItem[];
}
