/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MealOverview } from './mealOverview';

export interface DailyMenuResponse {
  soups?: MealOverview[];
  mainCourses?: MealOverview[];
}
