/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './alergen';
export * from './apiErrorResponse';
export * from './authResponse';
export * from './buffetItem';
export * from './buffetMenu';
export * from './dailyMenu';
export * from './dailyMenuResponse';
export * from './loginCredentials';
export * from './meal';
export * from './mealsHistory';
export * from './occupancyResponseDto';
export * from './occupancyResponseDtoOccupancy';
export * from './ratingResponse';
export * from './topUpRequest';
export * from './user';
export * from './weeklyMenu';