/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Meal } from './meal';

export interface MealsHistory {
  id?: number;
  date?: string;
  meal?: Meal;
  price?: number;
}
