/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Alergen } from './alergen';

export interface MealOverview {
  id?: number;
  name?: string;
  price?: number;
  alergenList?: Alergen[];
}
