/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OccupancyResponseDtoOccupancy } from './occupancyResponseDtoOccupancy';

/**
 * Data transfer object for returning weekly canteen occupancy.
 */
export interface OccupancyResponseDto {
  /** A map of occupancy where the key is the day of the week (MON-SUN) and the value is another map (hour:number of people amount). */
  occupancy?: OccupancyResponseDtoOccupancy;
}
