/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * A map of occupancy where the key is the day of the week (MON-SUN) and the value is another map (hour:number of people amount).
 */
export type OccupancyResponseDtoOccupancy = {[key: string]: {[key: string]: number}};
