/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DailyMenu } from './dailyMenu';

export interface WeeklyMenu {
  days?: DailyMenu[];
}
