/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  OccupancyResponseDto
} from '.././models';

import { api } from '.././axios';



  export const getCanteenOccupancy = () => {
/**
 * Returns data on the number of people in the canteen, broken down by day of the week and hour. Data is read from the canteen's JSON file.
 * @summary Gets current canteen occupancy data
 */
const getOccupancy = (
    canteen: string,
 ) => {
      return api<OccupancyResponseDto>(
      {url: `/occupancy/${canteen}`, method: 'GET'
    },
      );
    }
  return {getOccupancy}};
export type GetOccupancyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCanteenOccupancy>['getOccupancy']>>>
