/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  OccupancyResponseDto
} from '.././models';

import { api } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getCanteenOccupancy = () => {
/**
 * Returns data on the number of people in the canteen, broken down by day of the week and hour. Data is read from the canteen's JSON file.
 * @summary Gets current canteen occupancy data
 */
const getOccupancy = (
    canteen: string,
 options?: SecondParameter<typeof api<OccupancyResponseDto>>,) => {
      return api<OccupancyResponseDto>(
      {url: `/occupancy/${canteen}`, method: 'GET'
    },
      options);
    }
  return {getOccupancy}};
export type GetOccupancyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCanteenOccupancy>['getOccupancy']>>>
