/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  Alergen,
  Meal,
  MealsHistory,
  RatingResponse
} from '.././models';

import { api } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getMeals = () => {
/**
 * Retrieves a list of all meals available in the database.
 * @summary Get all meals
 */
const getAllMeals = (
    
 options?: SecondParameter<typeof api<Meal[]>>,) => {
      return api<Meal[]>(
      {url: `/meals`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves detailed information about a specific meal by its ID.
 * @summary Get meal details
 */
const getMeal = (
    id: number,
 options?: SecondParameter<typeof api<Meal>>,) => {
      return api<Meal>(
      {url: `/meals/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * Returns the number of likes and dislikes for a specific meal.
 * @summary Get meal ratings
 */
const getMealRatings = (
    id: number,
 options?: SecondParameter<typeof api<RatingResponse>>,) => {
      return api<RatingResponse>(
      {url: `/meals/${id}/rating`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves the historical price and availability data for a specific meal.
 * @summary Get meal history
 */
const getMealHistory = (
    id: number,
 options?: SecondParameter<typeof api<MealsHistory[]>>,) => {
      return api<MealsHistory[]>(
      {url: `/meals/${id}/history`, method: 'GET'
    },
      options);
    }
  /**
 * Returns a list of allergens associated with a specific meal.
 * @summary Get meal allergens
 */
const getMealAllergens = (
    id: number,
 options?: SecondParameter<typeof api<Alergen[]>>,) => {
      return api<Alergen[]>(
      {url: `/meals/${id}/allergens`, method: 'GET'
    },
      options);
    }
  return {getAllMeals,getMeal,getMealRatings,getMealHistory,getMealAllergens}};
export type GetAllMealsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeals>['getAllMeals']>>>
export type GetMealResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeals>['getMeal']>>>
export type GetMealRatingsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeals>['getMealRatings']>>>
export type GetMealHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeals>['getMealHistory']>>>
export type GetMealAllergensResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMeals>['getMealAllergens']>>>
