/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Alergen,
  Meal,
  MealsHistory,
  RatingResponse
} from '.././models';




  /**
 * Retrieves a list of all meals available in the database.
 * @summary Get all meals
 */
export const getAllMeals = <TData = AxiosResponse<Meal[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/meals`,options
    );
  }
/**
 * Retrieves detailed information about a specific meal by its ID.
 * @summary Get meal details
 */
export const getMeal = <TData = AxiosResponse<Meal>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/meals/${id}`,options
    );
  }
/**
 * Returns the number of likes and dislikes for a specific meal.
 * @summary Get meal ratings
 */
export const getMealRatings = <TData = AxiosResponse<RatingResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/meals/${id}/rating`,options
    );
  }
/**
 * Retrieves the historical price and availability data for a specific meal.
 * @summary Get meal history
 */
export const getMealHistory = <TData = AxiosResponse<MealsHistory[]>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/meals/${id}/history`,options
    );
  }
/**
 * Returns a list of allergens associated with a specific meal.
 * @summary Get meal allergens
 */
export const getMealAllergens = <TData = AxiosResponse<Alergen[]>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/meals/${id}/allergens`,options
    );
  }
export type GetAllMealsResult = AxiosResponse<Meal[]>
export type GetMealResult = AxiosResponse<Meal>
export type GetMealRatingsResult = AxiosResponse<RatingResponse>
export type GetMealHistoryResult = AxiosResponse<MealsHistory[]>
export type GetMealAllergensResult = AxiosResponse<Alergen[]>
