/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AuthResponse,
  LoginCredentials
} from '.././models';

import { api } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAuthentication = () => {
/**
 * Authenticates a user with username and password.
 * @summary User login
 */
const login = (
    loginCredentials: LoginCredentials,
 options?: SecondParameter<typeof api<AuthResponse>>,) => {
      return api<AuthResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginCredentials
    },
      options);
    }
  return {login}};
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthentication>['login']>>>
