/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BuffetMenu,
  DailyMenuResponse,
  WeeklyMenu
} from '.././models';




  /**
 * Retrieves the weekly menu for the specified canteen.
 * @summary Get weekly menu
 */
export const getMenu = <TData = AxiosResponse<WeeklyMenu>>(
    canteen: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/menu/${canteen}`,options
    );
  }
/**
 * Retrieves the daily menu for a specific canteen and date.
 * @summary Get daily menu
 */
export const getMenu1 = <TData = AxiosResponse<DailyMenuResponse>>(
    canteen: string,
    date: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/menu/${canteen}/${date}`,options
    );
  }
/**
 * Retrieves the buffet menu for a specific canteen.
 * @summary Get buffet menu
 */
export const getBuffetMenu = <TData = AxiosResponse<BuffetMenu>>(
    canteen: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/menu/${canteen}/buffet`,options
    );
  }
export type GetMenuResult = AxiosResponse<WeeklyMenu>
export type GetMenu1Result = AxiosResponse<DailyMenuResponse>
export type GetBuffetMenuResult = AxiosResponse<BuffetMenu>
