/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  BuffetMenu,
  DailyMenuResponse
} from '.././models';

import { api } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getMenu = () => {
/**
 * Retrieves the daily menu for a specific canteen and date.
 * @summary Get daily menu
 */
const getMenu = (
    canteen: string,
    date: string,
 options?: SecondParameter<typeof api<DailyMenuResponse>>,) => {
      return api<DailyMenuResponse>(
      {url: `/menu/${canteen}/${date}`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves the buffet menu for a specific canteen.
 * @summary Get buffet menu
 */
const getBuffetMenu = (
    canteen: string,
 options?: SecondParameter<typeof api<BuffetMenu>>,) => {
      return api<BuffetMenu>(
      {url: `/menu/${canteen}/buffet`, method: 'GET'
    },
      options);
    }
  return {getMenu,getBuffetMenu}};
export type GetMenuResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['getMenu']>>>
export type GetBuffetMenuResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['getBuffetMenu']>>>
